```{r}
library(tidyverse)
library(lme4)
library(ggpirate)
library(ggplot2)
library(ggpirate)
library(dplyr)

```

```{r}
FR <- read.csv("/Users/madisonparon/Documents/GitHub/james2021/data/pilot/PilotB_cleandata/PilotB_recognition_combined_day1_day2.csv", header=TRUE)
```

Descriptive statistics
```{r}
FR$neighb <- fct_relevel(FR$neighb, c("none", "one", "many")) # order for intuitive printing of means 

FR %>%
  group_by(session) %>%
  summarise(mean = mean(acc), sd = sd(acc))

```
```{r}
FR %>%
  group_by(neighb) %>%
  summarise(mean = mean(acc), sd = sd(acc))
```

```{r}
FR %>%
  group_by(session, neighb) %>%
  summarise(mean = mean(acc), sd = sd(acc))
```

Preparation for analysis

Word Neighbors
```{r}
neighb.contrasts <- cbind(c(-2, 1, 1), c(0,-1,1))
contrasts(FR$neighb) <- neighb.contrasts
contrasts(FR$neighb)
```
Test Session
```{r}
FR$session <- as.factor(FR$session)
session.contrasts <- cbind(c(-2, 1, 1), c(0,-1,1))
contrasts(FR$session) <- session.contrasts
contrasts(FR$session)
```
Vocabulary ability
```{r}
recog$vocabS <- scale(recog$vocabRaw, center = TRUE, scale = TRUE) 
```

Is performance at above chance levels?
```{r}
# Compute participant means for the first session
pptMeans <- FR %>%
  select(ID, session, acc) %>%
  filter(session == 1) %>%
  group_by(ID) %>%
  summarise(mean = mean(acc, na.rm = TRUE))
```

```{r}
# Perform one-sample t-test against chance performance (.5)
t.test(pptMeans$mean, mu=.5, alternative = "greater")
```
Model building
Pruning of fixed effects
```{r}
# Full model with interaction of session and neighb only
fix.full <- glmer(acc ~ session*neighb + (1|ID) + (1|item),
                  data = FR, family = binomial,
                  control = glmerControl(optimizer = "bobyqa"))
```
```{r}
fix.pars <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1|ID) + (1|item), 
                  data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa"))
anova(fix.pars, fix.full)
```

Build random effects structure
```{r}
# Model without random effects for participants
mod.items <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1|item), 
                   data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa")) 
anova(mod.items, fix.pars) 

```


```{r}
# Model without random effects for items
mod.ppts <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1|ID), 
                  data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa"))
anova(mod.ppts, fix.pars)
```

By-participant random slopes

```{r}
# Model with by-participant slopes for the effect of session
mod1 <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1+session|ID) + (1|item), 
              data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa"))
```

```{r}
anova(fix.pars, mod1)
```

```{r}
# Model with by-participant slopes for the effect of neighbour condition
mod2 <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1+neighb|ID) + (1|item), 
              data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa"))
anova(fix.pars, mod2)
```

```{r}
# Model with by-participant slopes for the effects of neighbour condition and test session
mod2a <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1+neighb+session|ID) + (1|item), 
               data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa"))
```

```{r}
anova(mod2, mod2a)
```

By-item random slopes
```{r}
# Model with by-item slopes for the effects of test session
mod3 <- glmer(acc ~ session*neighb + vocabS*neighb + session*vocabS + (1+neighb|ID) + (1+session|item), 
               data = PR, family = binomial, control = glmerControl(optimizer = "bobyqa"))
```


```{r}
anova(mod2, mod4) 
```

Final model
The final model we arrived at is as follows:
```{r}
summary(mod2)
```

Plot Graphs

```{r}
##Compute participant condition means
cond.means <- FR %>%
  group_by(ID, session, neighb) %>%
  summarise(mean = mean(acc, na.rm = TRUE))

cond.means$session <- as.factor(cond.means$session)
```

```{r}
formGraph <- ggplot(data = cond.means, aes(x = session, y = mean)) +
  theme_bw() +
  geom_pirate(aes(colour = neighb, fill = neighb),
              show.legend   = TRUE,
              points_params = list(alpha = 1, size = 3),
              lines_params  = list(size = 0.9)) +
  scale_color_discrete(name = "Word-form neighbours:") +
  scale_fill_discrete(name = "Word-form neighbours:") +
  scale_x_discrete(
    name   = "Test session",
    breaks = c("1", "2"),           # use c("1","2","3") if you have 3 sessions
    labels = c("Same day", "Next day")
    # labels = c("Same day","Next day","Week later") for 3 sessions
  ) +
  scale_y_continuous(name = "Proportion correct") +
  theme(
    legend.position       = "top",
    legend.title          = element_text(size = 14),
    legend.text           = element_text(size = 14),
    legend.box.background = element_rect(colour = "black"),
    strip.text            = element_text(size = 20),
    axis.title            = element_text(size = 18),
    axis.text             = element_text(size = 14)
  ) +
  geom_hline(yintercept = 0.50, linetype = "dashed")

print(formGraph)

```
```{r}
# Save as a ggplot object
saveRDS(formGraph, file = "formGraph.rds")
```


R Version information
```{r}
sessionInfo()

```

